
POST https://booking-system-explore-booking.herokuapp.com/places
Content-Type: application/json

{
    "place": "Lifecycle",
    "location": "lifestyle",
    "img": "asdfghj",
    "category": "yfbdnskm",
    "description": "boring",
    "price": "0123456"  
}