GET https://booking-system-explore-booking.herokuapp.com/places
###

POST https://booking-system-explore-booking.herokuapp.com/places
Content-Type: application/json

{
"place": "LifeChoices",
"location": "64 New Church St, Tamboerskloof, Cape Town, 8018",
"img": 
 "https://lh3.googleusercontent.com/p/AF1QipM9FHr1C9TP392ydMmQVqAbeUFWElu-f676lQ5v=w296-h202-n-k-rw-no-v1",

"category": "Hotel",
"description": "Chic rooms with free WiFi, plus an outdoor pool, a restaurant, a lounge bar and free bike rental.",
"price": "118"
}
###

PUT https://booking-system-explore-booking.herokuapp.com/places/
Content-Type: application/json

{
 "place": "",
 "location": "",
 "img": "",
 "catergory": "",
 "description": "",
 "price": ""
}
###


DELETE https://booking-system-explore-booking.herokuapp.com/places/6242ee80956fca7308bf3cc9
###

####################################################################################
GET https://booking-system-explore-booking.herokuapp.com/users
###

GET https://booking-system-explore-booking.herokuapp.com/users/
###

POST https://booking-system-explore-booking.herokuapp.com/users/login
Content-Type: application/json

{
  "name": "teddy",
  "phone_number": "1234567890",
  "email": "teddy@gmail.com",
  "password": "0123456789"
}
###

PUT https://booking-system-explore-booking.herokuapp.com/users/62432473b76de8a168421fa0
Content-Type: application/json

{
  "name": "Inathi",
  "phone_number": "0123456789",
  "email": "bsdfg@gmail.com",
  "password": "0123456789"
}

###
DELETE https://booking-system-explore-booking.herokuapp.com/users/62432473b76de8a168421fa0
Content-Type: application/json
###
