POST https://booking-system-explore-booking.herokuapp.com/places
Content-Type: application/json

{
"place": "Protea Hotel Fire & Ice!",
"location": "64 New Church St, Tamboerskloof, Cape Town, 8018",
"img": {
  "0": "https://lh3.googleusercontent.com/p/AF1QipM9FHr1C9TP392ydMmQVqAbeUFWElu-f676lQ5v=w296-h202-n-k-rw-no-v1",
  "1": "https://lh3.googleusercontent.com/p/AF1QipM9LqepbBst5pZDmA_hPhkGwMbGz0o4q2cfF8NP=w296-h202-n-k-rw-no-v1",
  "2": "https://lh3.googleusercontent.com/p/AF1QipNC_qZ0pORXRpKIhh31EYTCZ6E2aS7aCh1Bs1Lo=w296-h202-n-k-rw-no-v1",
  "3": "https://lh3.googleusercontent.com/p/AF1QipOMB5hT16iSfHZAVwHgO_LI33btk9mhFoNGzOyh=w296-h202-n-k-rw-no-v1"
},
"category": "Hotel",
"description": "Chic rooms with free WiFi, plus an outdoor pool, a restaurant, a lounge bar and free bike rental.",
"price": "1.18"
}

###
POST https://booking-system-explore-booking.herokuapp.com/user/signup
Content-Type: application/json

{
  "name": "Teddy",
  "phone_number":"0123456889",
  "email": "teddy@gmail.com",
  "password": "0123456789"
}
###
GET https://booking-system-explore-booking.herokuapp.com/users
c